[package]
# Publishing requires maintainers to declare the project license first.
publish = false
name = "sas"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { workspace = true }
soroban-sas-common = { path = "../../packages/soroban-sas-common" }

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
ed25519-dalek = "2.0.0"
hex = "0.4"
schema-registry = { path = "../schema-registry", features = ["testutils"] }
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-strkey = "0.0.8"
